{
 "title": "Custom Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(up{job=~\"custom_exporter\"},job)"
    }
   },
   {
    "name": "API",
    "query": {
     "query": "label_values(api_success_total{job=\"$job\"},api)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Latency (rate(sum)/rate(count))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(api_latency_seconds_sum[5m]) / rate(api_latency_seconds_count[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC Volatility — Last 1h",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "stddev_over_time(crypto_btc_usd[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Requests per Second — Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (api) (rate(api_success_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Combined time of all queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "api_latency_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PM2.5 — 1h Average",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(air_pm25_ugm3[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AQI — 1h Max",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(air_us_aqi[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "weather_humidity_percent\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed — 30-min Median",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, weather_wind_speed_ms[30m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Temperature — Last 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_c[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "weather_temperature_c\r\n", "legendFormat": "__auto" }
   ]
  }
 ]
}