{
 "title": "Database exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pg_job",
    "query": {
     "query": "label_values(up{job=~\"$pg_job\"},job)"
    }
   },
   {
    "name": "query0",
    "query": {
     "query": "label_values(up{job=~\"$pg_job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(api_latency_seconds_sum[5m]) / rate(api_latency_seconds_count[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(pg_stat_database_blks_hit[5m]))\r\n/\r\nsum(rate(pg_stat_database_blks_hit[5m]) + rate(pg_stat_database_blks_read[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(pg_stat_database_xact_commit[5m]) +\r\n  rate(pg_stat_database_xact_rollback[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_user_tables_rows_rows", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of users ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_roles_connection_limit)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted[5m]) + rate(pg_stat_database_tup_updated[5m]) + rate(pg_stat_database_tup_deleted[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "pg_user_tables_count_tables\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction rate TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[5m]) + rate(pg_stat_database_xact_rollback[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\", job=\"postgres_exporter\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database size (GB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by(database)(pg_db_size_bytes_by_name_bytes) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}