FROM python:3.11-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates tzdata \
 && update-ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY custom_exporter.py .

RUN pip install --no-cache-dir requests prometheus_client

EXPOSE 8000
CMD ["python", "custom_exporter.py"]
