{
 "title": "Node exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"node-windows\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summed traffic Mb/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  irate(node_network_receive_bytes_total{}[1m]) +\r\n  irate(node_network_transmit_bytes_total{}[1m])\r\n) / 1024^2\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disc memory ocuppied %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  windows_logical_disk_free_bytes{ instance=\"$instance\"}\r\n  /\r\n  windows_logical_disk_size_bytes{ instance=\"$instance\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windows_system_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU total usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - avg(rate(windows_cpu_time_total{mode=\"idle\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic (Incoming / Outgoing, Mbit/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_total[1m]) / 1024^2",
     "legendFormat": "__auto"
    },
    {
     "expr": "8 * irate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]) / 1e6\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O — Read / Write (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[5m])\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average (1,5,15)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1\r\n\r\n", "legendFormat": "__auto" },
    { "expr": "node_load5\r\n", "legendFormat": "__auto" },
    { "expr": "node_load15\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Disk Space (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume=\"C:\"} / 1024^3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}